# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cm < Formula
  desc "Container monitor - stream Docker compose logs with a beautiful TUI"
  homepage "https://github.com/rehrumesh/cm"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rehrumesh/cm/releases/download/v0.2.0/cm_0.2.0_darwin_amd64.tar.gz"
      sha256 "9f5671c9c66edfd4bec987482c4632bea0de151b43e70ee769a3c7aada241aed"

      def install
        bin.install "cm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rehrumesh/cm/releases/download/v0.2.0/cm_0.2.0_darwin_arm64.tar.gz"
      sha256 "2ab84063fca79dc31d9e7c35ac4ba721b37d549ae3bab730cee89144b02f78ce"

      def install
        bin.install "cm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rehrumesh/cm/releases/download/v0.2.0/cm_0.2.0_linux_amd64.tar.gz"
      sha256 "22630073d9594105bbaf33633f2058efd280e60fcc15e7841151c3948ef53757"
      def install
        bin.install "cm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rehrumesh/cm/releases/download/v0.2.0/cm_0.2.0_linux_arm64.tar.gz"
      sha256 "4488ed1404ff52b6c9c82b05157b5f3544f7b900d467f7f569d3a996ff2093ff"
      def install
        bin.install "cm"
      end
    end
  end

  test do
    system "#{bin}/cm", "--version"
  end
end
