# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cm < Formula
  desc "Container monitor - stream Docker compose logs with a beautiful TUI"
  homepage "https://github.com/rehrumesh/cm"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rehrumesh/cm/releases/download/v0.3.0/cm_0.3.0_darwin_amd64.tar.gz"
      sha256 "44c625bf7888ad263126ca01f3b37782ad41fbf38d5b8b50d7fe12439fdfeb10"

      def install
        bin.install "cm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rehrumesh/cm/releases/download/v0.3.0/cm_0.3.0_darwin_arm64.tar.gz"
      sha256 "97f27d9cb53d08f3e486a91d143c70fa9ac26ab3116edd1aba8bf394be65153c"

      def install
        bin.install "cm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rehrumesh/cm/releases/download/v0.3.0/cm_0.3.0_linux_amd64.tar.gz"
      sha256 "dfd9a6c271d8f8ea7b1acc10b64f03ca505f90d018366252a83c95b563fa0c3e"
      def install
        bin.install "cm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rehrumesh/cm/releases/download/v0.3.0/cm_0.3.0_linux_arm64.tar.gz"
      sha256 "2bcc85183391b141059284e3d32c22f942a0c5be37431e0f1f0d80e2cdccf007"
      def install
        bin.install "cm"
      end
    end
  end

  test do
    system "#{bin}/cm", "--version"
  end
end
