# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cm < Formula
  desc "Container monitor - stream Docker compose logs with a beautiful TUI"
  homepage "https://github.com/rehrumesh/cm"
  version "1.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rehrumesh/cm/releases/download/v1.6.1/cm_1.6.1_darwin_amd64.tar.gz"
      sha256 "1f974dab2ab1ab889dd506b40474e752e6ae03f58a5efe5c716f5d7841571e0f"

      define_method(:install) do
        bin.install "cm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rehrumesh/cm/releases/download/v1.6.1/cm_1.6.1_darwin_arm64.tar.gz"
      sha256 "fec580608bf1b5e2c977ca3eb21aa032ca3e7afa3a53ff26161ec681e7c2a781"

      define_method(:install) do
        bin.install "cm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rehrumesh/cm/releases/download/v1.6.1/cm_1.6.1_linux_amd64.tar.gz"
      sha256 "0bfdc7d6c69eb4128bf933f5a9189fe0e8db09b79243e39cae2b66c835ef8437"
      define_method(:install) do
        bin.install "cm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rehrumesh/cm/releases/download/v1.6.1/cm_1.6.1_linux_arm64.tar.gz"
      sha256 "092bcb38122b80a79e0049b37581fce0a7abc7841e208c4af7d6c0a65c70199f"
      define_method(:install) do
        bin.install "cm"
      end
    end
  end

  test do
    system "#{bin}/cm", "--version"
  end
end
